### ISSUE TITLE
ElationOfProjectiveSpace panics in fields of characteristic two

### ISSUE THREAD

**Issue by Triagle** [gap-packages/FinInG#14]
If you attempt to use the method `ElationOfProjectiveSpace` using some (but not all) fields of characteristic two, it will cause a panic that is related ultimately to the `CONV_GF2VEC`. I notice that a bug Geertrui found in the very similar `ProjectiveElationGroup` method just needed a simple change to unpack the cvec returned by `UnderlyingObject(centre)`. Having made the same change on my own installation I found that changing line 2433 of `projectivespace.gi` to read
```gap
e0 := Unpack(UnderlyingObject(centre));
```
fixed the issue for me. Geertrui is the supervisor for my master's project, so it is quite a coincidence that we found these bugs independently (and seeking to do entirely different things as far as I can tell!). 

Here is some code you may reuse to reproduce this issue:
```gap
ps := PG(2, 8);
l := HyperplaneByDualCoordinates(ps, [1, 0, 0]*Z(8)^0);
p := VectorSpaceToElement(ps, [1, 0, 0]*Z(8)^0);
q := VectorSpaceToElement(ps, [1, 1, 0]*Z(8)^0);
ElationOfProjectiveSpace(l, p, q);
```
This will fail with the following stacktrace
```
Error, Panic: cannot convert <list> (is a data object) to a plain list in
  CONV_GF2VEC( v ); at /usr/lib/gap/lib/vecmat.gi:1370 called from 
ConvertToVectorRepNC( vc, f ); at /usr/lib/gap/lib/matrix.gi:2358 called from
SemiEchelonMat( gens ) at /usr/lib/gap/lib/vspcrow.gi:747 called from
BasisVectors( B ) at /usr/lib/gap/lib/basis.gi:84 called from
Length( list ) at /usr/lib/gap/lib/list.gi:560 called from
Unpack( Basis( ComplementSpace( vssub, [ e0 ] ) ) 
 ) at /usr/lib/gap/pkg/fining/lib/projectivespace.gi:2434 called from
...  at *stdin*:12
```

**Comment by fingolfin** [comment]
Thank you for the report and even providing the fix. I've submitted PR #18 to address this, and the next FinInG release should not have this issue anymore.
