### ISSUE TITLE
Update fininig.org

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/FinInG#20]
Right now, http://www.fining.org redirects to http://cage.ugent.be/fining/ -- I suggest that *both* of these should instead redirect to https://gap-packages.github.io/FinInG/ -- alternatively, the cage website should be modified to state that it is outdated.

As a variant, depending on what registrar you use to manage fining.org, we could set a `CNAME` DNS record that ensures that website actually is https://www.fining.org, but shows exactly the content of https://gap-packages.github.io/FinInG -- doing that is quite easy, I'd be happy to help set it up, too (I've done it plenty of times before). 

Who controls fining.org? Perhaps @jdebeule ?

As a slightly related concern, I see that you advertise email addresses `support@...` and `council@...` at this domain. Perhaps I could be added to those, so if users report issues this way, I will be made aware, too?

**Comment by jdebeule** [comment]
fining.org is now pointing to https://gap-packages.github.io/FinInG/, at least I made the change in the web forwarding panel of the provider. It might take up to some hours before this becomes effective. However, also the cage website is pointing now to https://gap-packages.github.io/FinInG/. I am happy with fining.org redirecting openly to https://gap-packages.github.io/FinInG/. 

Also, I added you to the support@ and council@ distribution list.
