### ISSUE TITLE
Allow output of FiningOrbits to be surpressed

### ISSUE THREAD

**Issue by ferihr** [gap-packages/FinInG#29]
Currently, line 132 in `lib/orbits-stabilisers.gi` reads `Print(upto, "%..\c");` and this can be annoying when this function is called very often. It would be nice if we could surpress this. For me I replaced it by `Info(InfoFinInG, 1, String(upto), "%..\c");`, but Info always prints a newline, so this is not an optimal solution.

(I hope that this is now the right place to report these things. The BitBucket tracker is no longer used if I understand correctly.)

**Comment by fingolfin** [comment]
Thank you for your report. Yes this is the right place for such reports.

Fixed in version 1.5.2 via 936ac7a4193c19f0f6d161446403319277703254
